color0 #101410
color1 #ffb4ab
color2 #8bd897
color3 #afcfb0
color4 #a3c9ff
color5 #8bd897
color6 #afcfb0
color7 #e0e4dc
color8 #899388
color9 #ffb4ab
color10 #8bd897
color11 #afcfb0
color12 #a3c9ff
color13 #8bd897
color14 #afcfb0
color15 #e0e4dc

cursor                #e0e4dc
cursor_text_color     #101410
background            #101410
foreground            #e0e4dc
selection_foreground  #bfc9bd
selection_background  #404940
active_border_color   #8bd897
inactive_border_color #404940
url_color             #8bd897

active_tab_foreground   #003916
active_tab_background   #8bd897
inactive_tab_foreground #bfc9bd
inactive_tab_background #404940
cursor_trail_color      #bfc9bd
