color0 #131314
color1 #ffb4ab
color2 #b6c9d9
color3 #c1c7ce
color4 #d4c0d8
color5 #b6c9d9
color6 #c1c7ce
color7 #e4e2e3
color8 #8d9196
color9 #ffb4ab
color10 #b6c9d9
color11 #c1c7ce
color12 #d4c0d8
color13 #b6c9d9
color14 #c1c7ce
color15 #e4e2e3

cursor                #e4e2e3
cursor_text_color     #131314
background            #131314
foreground            #e4e2e3
selection_foreground  #c3c7cb
selection_background  #43474b
active_border_color   #b6c9d9
inactive_border_color #43474b
url_color             #b6c9d9

active_tab_foreground   #20323f
active_tab_background   #b6c9d9
inactive_tab_foreground #c3c7cb
inactive_tab_background #43474b
cursor_trail_color      #c3c7cb
